### PR TITLE
Added support for multiple same entity detection

### LINKED ISSUE #168: update indexer to support multiple same entity detection
currently the entity field in the indexer is of type 'string'
and at the azure function for the custom skillset, we only add the first occurrence of the entity if found in the document
ex:
if our app had an entity "PersonName" 
there will be a field in the index called PersonName of type string
and when we call the azure function using one of the docs, and CT detects multiple occurences of "PersonName", only the first one will be added to the index

### PR DESCRIPTION
**Pull request by ZulaMostafa**
Closes #168.

In CLIIndexingTool: 
- Adjusted the create index method to make field type `Collection<string>`.

In CustomFunction:
- Entities are now grouped by their categories to insert all of the entities as a whole.

### CODE REVIEW

**Comment by mshaban-msft** [comment]
did you test out both azure function and indexing tool, in addition to viewing/searching the index?

**Comment by ZulaMostafa** [comment]
> did you test out both azure function and indexing tool, in addition to viewing/searching the index?

Yes I tested all that;
- for indexing: the entities will be created with type 'Collection(Edm.String)`
- for azure function: it groups the entities with their category and insert them as a collection of strings
- for searching: the entity type should be collection of string to be able to view it and search for it i.e: list of strings or string array

don't forget that you have to publish the function to apply the changes otherwise the indexer will fail.

**Comment by mshaban-msft** [comment]
> > did you test out both azure function and indexing tool, in addition to viewing/searching the index?
> 
> Yes I tested all that;
> 
> * for indexing: the entities will be created with type 'Collection(Edm.String)`
> * for azure function: it groups the entities with their category and insert them as a collection of strings
> * for searching: the entity type should be collection of string to be able to view it and search for it i.e: list of strings or string array
> 
> don't forget that you have to publish the function to apply the changes otherwise the indexer will fail.

i understand!
but did you actually re-publish the function and run the tool?!

**Comment by ZulaMostafa** [comment]
> > > did you test out both azure function and indexing tool, in addition to viewing/searching the index?
> > 
> > 
> > Yes I tested all that;
> > 
> > * for indexing: the entities will be created with type 'Collection(Edm.String)`
> > * for azure function: it groups the entities with their category and insert them as a collection of strings
> > * for searching: the entity type should be collection of string to be able to view it and search for it i.e: list of strings or string array
> > 
> > don't forget that you have to publish the function to apply the changes otherwise the indexer will fail.
> 
> i understand! but did you actually re-publish the function and run the tool?!

Yes ofc, I ran cli tool and tried searching using serchclient sdk to make sure everything works well

**Review by mshaban-msft — APPROVED** [review]

**Pull request merged**
